Repository wecode-bootcamp-korea/20-2nd-CREAM-frontend, pull requests merged in 2021-06, with the labels that each got.

#5 [20기 권오재] 메인탑배너, 도현님 중복 스타일드 컴포넌트 병합 리뷰 반영 완료
  public/images/topBanner_1.jpeg
  public/images/topBanner_2.jpeg
  public/images/topBanner_3.jpeg
  public/images/topBanner_4.jpeg
  public/images/topBanner_5.jpeg
  src/Routes.js
  src/pages/Main/Main.js
  src/pages/Main/MainTopBanner/Maintopbanner.js
Labels: Status: Accepted

#7 [20기 전용민] Add: 2021/06/01 기능구현 완료, 리뷰 반영, 백과의 통신 OK, merge 부탁드립니다!
  public/data/mypageData.json
  src/Routes.js
  src/config.js
  src/pages/Mypage/Mypage.js
Labels: Status: Accepted

#3 [20기 김수연] 상세페이지 데이터 fetch완료, 에러 및 버그 일부 수정
  package-lock.json
  package.json
  public/data/bidHistoryModal.json
  public/data/bidHistoryModal2.json
  public/data/chartData.json
  public/data/chartData2.json
  public/data/detailMockData.json
  public/data/recentDealData.json
  public/data/recentDealData2.json
  public/data/recentDealData3.json
  public/images/test1.jpeg
  public/images/test1.png
  public/images/test2.jpeg
  public/images/test2.png
  src/Routes.js
  src/components/Modal/Modal.js
  src/config.js
  src/pages/Detail/DealBtn/DealBtn.js
  src/pages/Detail/DealChart/DealChart.js
  src/pages/Detail/DealInfo/DealInfo.js
  src/pages/Detail/Detail.js
  src/pages/Detail/ModalContents/BidHistoryModal.js
  src/pages/Detail/ModalContents/PrecautionModal.js
  src/pages/Detail/ModalContents/RecentDealModal.js
  src/pages/Detail/ModalContents/SelectSize.js
  src/pages/Detail/Precautions/Precautions.js
  src/pages/Detail/ProductImg/ProductImg.js
  src/pages/Detail/ProductInfo/ProductInfo.js
  src/pages/Detail/Util/SizeBtn.js
  src/pages/Main.js
  src/styles/GlobalStyles.js
Labels: Status: 리뷰 요청

#13 [20기 김수연] 상세페이지 데이터 수정 버그 수정
  public/data/otherProduct.json
  src/config.js
  src/pages/Detail/DealChart/DealChart.js
  src/pages/Detail/Detail.js
  src/pages/Detail/ModalContents/SelectSize.js
  src/pages/Detail/OtherProducts/OtherProducts.js
  src/pages/Detail/Util/ProductBox.js
Labels: Status: Accepted

#10 [20기 권오재] Main.js, 필터 기능 함수 수정, 정렬 기능 구현완료 및 백엔드 통신 완료
  public/Data/Products.json
  src/components/ProductInfo.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/TypeBox.js
Labels: Status: 추가 기능 구현중

#8 [20기 전용민] Modify: 2021/6/3 구매 페이지 통신 후 로직 수정, conflict 해결
  package-lock.json
  public/data/buypageData.json
  src/Routes.js
  src/components/ProductThumbnail/ProductThumbnail.js
  src/components/ProductThumbnail/README.md
  src/config.js
  src/pages/BuyPage/BuyPage.js
Labels: Status: Accepted

#14 [20기 권오재] 레이아웃, Route 수정
  src/Routes.js
  src/components/Nav.js
  src/pages/Main/Main.js
  src/pages/Main/MainTopBanner/Maintopbanner.js
Labels: Status: 리뷰 요청

#16 [20기 김수연] footer 구현 완료, chart 일부 수정
  public/images/banner1.png
  public/images/banner2.gif
  public/images/funny1.png
  public/images/funny2.jpg
  src/Routes.js
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#17 [20기 전용민] Modify: 2021/06/04 Nav 조건부 렌더링, 로그인 페이지 초기화 오류 수정, 구매 및 판매페이지 경로 수정(수연님 branch merge 후에 merge 부탁드립니다!!.)
  public/index.html
  src/components/Nav.js
  src/pages/BuyPage/BuyPage.js
  src/pages/Login/Login.js
  src/pages/SellPage/SellPage.js
Labels: Status: 리뷰 요청

#18 [20기 권오재] Nav.js Nav Modal 검색 기능 추가 완료
  src/components/Modal/Modal.js
  src/components/Nav.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#19 [20기 김수연] 마지막 상세 페이지 버그 수정 완료
  src/pages/Detail/DealChart/DealChart.js
  src/pages/Detail/DealInfo/DealInfo.js
  src/pages/Detail/Detail.js
  src/pages/Detail/ModalContents/BidHistoryModal.js
  src/pages/Detail/ModalContents/RecentDealModal.js
  src/pages/Detail/ProductImg/ProductImg.js
  src/pages/Detail/ProductInfo/ProductInfo.js
Labels: Status: 리뷰 요청
